version: '3.8'
services:
  backend:
    container_name: backend
    build: .
    ports:
       - 8080:8080
    restart: unless-stopped
    depends_on:
       - postgres
    networks:
      - backend
  postgres:
    container_name: postgres-db
    image: postgres:13.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    name: backend
    driver: bridge
